# Generated by Django 4.2.4 on 2023-08-19 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_typeofwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacansy',
            name='freelanceType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.typeofwork'),
        ),
    ]
