# Generated by Django 4.2.4 on 2023-08-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_vacansy_freelancetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacansy',
            name='freelanceType',
        ),
        migrations.DeleteModel(
            name='typeOfWork',
        ),
    ]
