# Generated by Django 4.2.4 on 2023-08-25 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_vacansy_title_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='vacansy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.vacansy'),
        ),
    ]
