# Generated by Django 4.2.4 on 2023-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_apply_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='telegram',
            field=models.CharField(default='', max_length=100),
        ),
    ]
